openapi: 3.0.0
info:
  title: OpenPDS API
  version: 1.0.0
paths:
  /v1/transfers:
    get:
      operationId: ListTransfers
      responses:
        "200":
          description: List transfers.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransfersList"
    post:
      operationId: CreateTransfer
      requestBody:
        $ref: "#/components/requestBodies/TransferCreate"
      responses:
        "200":
          description: Create a transfer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"

  /v1/transfers/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: GetTransfer
      responses:
        "200":
          description: Get a transfer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"
    put:
      operationId: UpdateTransfer
      responses:
        "200":
          description: Update a transfer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"
    delete:
      operationId: DeleteTransfer
      responses:
        "200":
          description: Delete a transfer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"

  /v1/transfers/{id}/cancel:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: CancelTransfer
      responses:
        "200":
          description: Cancel a transfer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"

  /v1/transfers/{id}/confirm:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: ConfirmTransfer
      responses:
        "200":
          description: Confirm a transfer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transfer"

  /v1/providers:
    get:
      operationId: ListProviders
      responses:
        "200":
          description: List providers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Provider"

    post:
      operationId: CreateProvider
      responses:
        "200":
          description: Register a provider.
          content:
            application/json:
              schema:
                type: object
        "503":
          description: netdata daemon not ready (used for health checks).

  /v1/receiving-methods/check:
    post:
      operationId: CheckReceivingMethod
      requestBody:
        $ref: "#/components/requestBodies/ReceivingMethodCheck"
      responses:
        "200":
          description: Check a receiving method.
          content:
            application/json:
              schema:
                type: object
  /v1/receiving-methods/fetch:
    post:
      operationId: FetchReceivingMethod
      requestBody:
        $ref: "#/components/requestBodies/ReceivingMethodCheck"
      responses:
        "200":
          description: Retrieve a receiving method.
          content:
            application/json:
              schema:
                type: object

  /v1/receiving-methods:
    parameters:
      - in: query
        name: receiving_method
        style: deepObject
        explode: true
        schema:
          type: object
          properties:
            msisdn:
              type: string
      - in: query
        name: provider_id
        schema:
          type: integer
    get:
      operationId: GetReceivingMethod
      responses:
        "200":
          description: Fetch receiving method.
          content:
            application/json:
              schema:
                type: object

  /v1/connectors:
    get:
      operationId: ListConnectors
      responses:
        "200":
          description: List connectors.
          content:
            application/json:
              schema:
                type: object

components:
  requestBodies:
    TransferCreate:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TransferCreate"
    ReceivingMethodCheck:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              provider_id:
                type: integer
                format: int64
              receiving_method:
                type: object
              receiving_customer:
                type: object
              receiving_business:
                type: object
    ReceivingMethodFetch:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              receiving_method:
                type: object

  schemas:
    TransferCreate:
      type: object
      properties:
        third_party_reference:
          type: string
        delivery_method:
          type: string
          enum:
            - BANK
            - MOBILE_WALLET
        provider_id:
          type: string
        sending_method:
          $ref: "#/components/schemas/ReceivingMethod"
        receiving_method:
          $ref: "#/components/schemas/ReceivingMethod"
        receiving_currency:
          type: string
        receiving_amount:
          type: number
        sending_currency:
          type: string
        sending_amount:
          type: number
        sending_business:
          type: object
        sending_customer:
          type: object
        receiving_business:
          type: object
        receiving_customer:
          type: object

    Provider:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: FooBar

    ReceivingMethod:
      type: object
      properties:
        msisdn:
          type: string
        account_number:
          type: string

    Transfer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        return_url:
          type: string
        delivery_method:
          type: string
          enum:
            - BANK_TRANSFER
            - MOBILE_TRANSFER
        transfer_type:
          type: string

    TransfersList:
      type: object
      properties:
        payments:
          type: array
          items:
            $ref: "#/components/schemas/Transfer"
